ecom_proj/cart/urls.py
from django.urls import path
from . import  views

app_name='cart'
urlpatterns = [
    path('add/<int:prod_id>/',views.addCart,name='add_cart'),
    path('cart/details/',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove,name='remove_cart'),
    path('delete/<int:product_id>',views.delete,name='delete')
   ]

ecom_proj/ecom_app/urls.py
from django.urls import path
from . import  views

app_name='ecom'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='prodByCat'),
    path('<slug:c_slug>/<slug:p_slug>/', views.prodDetail, name='prodByCatDetail'),
]

ecom_proj/ecom_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls')),
    path('search_app',include('search_app.urls')),
    path('cart_app/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecom_proj/search_app/urls.py
from django.urls import path
from . import  views

app_name='search_app'
urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecom_proj/cart/models.py
from django.db import models
from ecom_app.models import  Product
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecom_proj/ecom_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField()
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural ='categories'

    def get_url(self):
        return  reverse('ecom:prodByCat',args=[self.slug])

    def __str__(self):
        return  '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available= models.BooleanField(default=True)
    created=models.DateField(auto_now=True)
    updated=models.DateField(auto_now=True)

    def get_url(self):
        return  reverse('ecom:prodByCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecom_proj/search_app/models.py
from django.db import models

# Create your models here.

ecom_proj/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from ecom_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def addCart(request, prod_id):
    product = Product.objects.get(id=prod_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()

    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    # print('***')
    # return HttpResponse("here")
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except Cart.DoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def delete(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

def index(request):
    return render(request, "cart.html")

ecom_proj/ecom_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import  Paginator,EmptyPage,InvalidPage
# Create your views here.
def home(request):
    return render(request,'home.html')

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)

    paginator=Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1

    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)


    print(products.object_list)
    return render(request,"category.html",{'category':c_page,'products':products})


def prodDetail(request,c_slug,p_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise

    return render (request,"product.html",{'product':product})

ecom_proj/search_app/views.py
from django.shortcuts import render
from ecom_app.models import Product
from django.db.models import  Q
# Create your views here.

def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains = query))
        return render (request,"search.html",{'query':query,'products':products})

ecom_proj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" integrity="" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">
    <script src="https://kit.fontawesome.com/64a4a72528.js" crossorigin="anonymous"></script>
    <meta name="description" content="{%  block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecom_proj/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{%  block metadescription %}
This is the cart page
{% endblock %}

{% block title %}
Ecom Pvt Ltd
{% endblock %}

{% block content %}
{% if not cart_items %}

<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Shopping Cart Is Empty.
        </h1>
        <br>
        <p class="text-center ">
            Please click <a href="{% url 'ecom:allProdCat' %}"> here</a> to continue shopping.
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>

<div class="row mx-auto">
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{ cart_item.product.get_absolute_url }}">
                        <img class="float-left rounded custom_image" src="{{ cart_item.product.image.url }}" alt="" style="width:100px;height:100px;"/>
                    </a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price: {{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item.product.price}}
                </td>
                <td>
                    $ {{ cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a class=custom_a" href="{% url 'cart:add_cart' cart_item.product.id %}">
                        <i class="fa-solid fa-plus custom_icon"></i>
                    </a>&nbsp
                    <a class=custom_a" href="{% url 'cart:remove_cart'   cart_item.product.id  %}">
                        <i class="fa-solid fa-minus custom_icon"></i>
                    </a>&nbsp
                    <a class=custom_a" href="{% url 'cart:delete' cart_item.product.id %}">
                        <i class="fa-solid fa-trash custom_icon"></i>
                    </a>
                </td>
                {% else %}
                <td>
                    <a class=custom_a" href="{% url 'cart:remove_cart'  cart_item.product.id  %}">
                        <i class="fa-solid fa-minus custom_icon"></i>
                    </a>&nbsp
                    <a class=custom_a" href="{% url 'cart:delete' cart_item.product.id %}">
                        <i class="fa-solid fa-trash custom_icon"></i>
                    </a>
                </td>
                {% endif %}

            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>Checkout</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total Is : <strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecom:allProdCat' %}" class="btn btn-secondary btn-block my_custom_btn"> Continue Shopping</a>

        </div>
    </div>
</div>


</div>
{% endif %}
{% endblock %}

ecom_proj/templates/category.html
{% extends 'base.html' %}
{% load static %}

{%  block metadescription %}
{% if category %}
{{ category.desc|truncatewords:150}}
{% else %}
Welcome to Ecom Store
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
{{ category.name}}
{% else %}
See our Collections
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row_class ">
        <div class="mx-auto">
            <p>
                <a href="{% url 'ecom:allProdCat'%}">Our Products Collection</a>{{category.name}}
            </p>
        </div>
    </div>
</div>
{% endif %}

{% if category %}
<div class="mx-auto">
    <img class="my_image my_image_padding" src="{{ category.image.url }}" alt="{{ category.name }}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify ">{{category.desc}}</p>
</div>
{% else %}
<div class="mx-auto">
    <img class="my_image my_image_padding" src="{% static 'img/ban.png'%}" alt="All Products" width="100%">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Product Collections</h1>
    <p class="text-justify ">orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of</p>
</div>
{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center " style="min-width:18em">
                <a href="{{product.get_url}}">
                    <img  class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            </div>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn bt-sm btn-light {% if products.number ==  pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

ecom_proj/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copy; ECOM Tech Private Ltd.</p>
</div>

ecom_proj/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecom:allProdCat' %}">
            <img src="{% static 'img/logo.png' %}" width="80px" height="80px"/>
        </a>
    </center>

</header>

ecom_proj/templates/home.html
{% extends 'base.html' %}
{%  block metadescription %}
Home
{% endblock %}
{% block content %}
{% endblock %}

ecom_proj/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecom:allProdCat'%}">Home</a>
                </li>
                <li class="nav-item dropdown {% if 'ecom' in request.path %} active {% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Ecom
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'ecom:allProdCat'%}">All Products</a></li>
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i> ({{item_count}})</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
</nav>

ecom_proj/templates/product.html
{% extends 'base.html' %}
{% load static %}

{%  block metadescription %}
{{ product.desc|truncatewords:150}}
{% endblock %}

{% block title %}
{{ product.name}}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p>
            <a href="{% url 'ecom:allProdCat' %}">Home</a>|
            <a href="{{ product.category.get_url}}">{{product.category}}</a>|
            {{ product.name }}
        </p>
    </div>
</div>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12  col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{product.image.url}}" alt="{{product.name}}"/>
            </div>
        </div>

        <div class="col-12 col-md-12 col-sm-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text"> {{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-secondary">Add to cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecom_proj/templates/search.html
{% extends 'base.html' %}
{% load static %}

{%  block metadescription %}
We have variety of products.
{% endblock %}

{% block title %}
Your Search Result Here
{% endblock %}

{% block content %}

<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b> </p>
</div>

<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center " style="min-width:18em">
                <a href="{{product.get_url}}">
                    <img  class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
            </div>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
        </div>

        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text">0 Results Found</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}